### ISSUE TITLE
StringTable == nullptr

### ISSUE THREAD

**Issue by rv32ima** [bl-launcher-plus/library#3]
https://github.com/bl-launcher-plus/library/blob/f0038f33f359da77f83a57c5d4bccfb6990da642/source/torque/torque.cpp#L74

This is not good. We cannot insert strings into the string table, and we cannot do **ANYTHING** that involves registering ConsoleFunctions, variables, etc.

**Comment by McTwist** [comment]
Could be the conversion that is broken. I thought it was odd at first, as there was no information about why this worked at first. I want it to be a pointer, but if it doesn't work then we could take it back.
